require:
  - rubocop-rspec

AllCops:
  SuggestExtensions: true
  NewCops: enable
  TargetRubyVersion: 3.2

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/Documentation:
  Enabled: false

# RSpec cops
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
